const translations = {
  fr: {
    welcome: "Bienvenue sur AVotey",
    subtitle: "Une plateforme de scrutins sécurisés",
    account: "Compte",
    greeting: "Bonjour",
    please_login: "Veuillez vous connecter.",
    logout: "Se déconnecter",
    enable_notifications: "Activer Notifications",
    disable_notifications: "Désactiver Notifications",
    email: "Email :",
    valid_email: "Email valide",
    password: "Password :",
    min_characters: "Minimum 8 caractères",
    login: "Login",
    register: "Register",
    email_placeholder: "abc@xyz.fr",
    password_placeholder: "******",
    question_placeholder: "Question ... ?",
    scrutins: "Scrutins",
    must_login_scrutins: "Vous devez être connecté pour intéragir avec les scrutins",
    gerer_listes: "Gérer mes listes",
    create_scrutin: "Créer un scrutin",
    voir_scrutins: "Voir mes scrutins",
    voter_scrutin: "Voter pour un structin",
    resultat_scrutin: "Résultat pour un structin",
    add_list: "Ajouter une liste",
    question: "Question :",
    question_help: "Cette question sera posée aux votants.",
    systeme_vote: "Système de vote :",
    uninominal: "Uninominal",
    jugement_majoritaire: "Jugement Majoritaire",
    choice: "Choix :",
    choices_help: "Ces choix seront proposés aux votants.",
    add_choice: "Ajouter un choix",
    predefined_choices: "Choix prédéfinis :",
    add_from_list: "Ajouter depuis une liste",
    binary: "Binaire",
    voters: "Votants :",
    voters_help: "Ces votants pourront voter au scrutin. Maximum 2 procurations.",
    add_voter: "Ajouter un votant",
    liste_votants: "Liste de votants :",
    create_ballot: "Créer le scrutin",
    filters: "Filtres :",
    filter_votable: "Votable",
    filter_resultats: "Résultats",
    filter_createur: "Créateur",
    list: "Liste :",
    organizer: "Organisateur",
    question_col: "Question",
    infos: "Infos",
    rights: "Droits",
    actions: "Actions",
    n_scrutin: "N° Scrutin",
    placeholder_via_voir: "Veuillez passer par 'Voir mes scrutins' pour pouvoir voter",
    help_n_scrutin: "Ceci représente le numéro du scrutin au quel vous allez voter.",
    systeme_vote_scrutin: "Système de Vote",
    help_systeme_vote: "Répresente le système de vote.",
    public_key: "Clé publique",
    vote_encrypted: "Le vote sera chiffré.",
    choice_uninominal: "Choix Uninominal",
    choose_proposal: "Veuillez choisir une proposition.",
    choice_jugement: "Choix Jugement Majoritaire",
    votez_proposition: "Veuillez votez pour une proposition.",
    vote_for_ballot: "Voter pour le scrutin",
    results: "Résultats :",
    absolute: "Absolu",
    percent_voters: "% Votants",
    percent_inscrits: "% Inscrits",
    repartition: "Répartition",
    mention: "Mention",
    download_pdf: "Télécharger en PDF",
    footer_text: "<strong>AVotey</strong> par Jessy FALLAVIER. Projet universitaire. Licence : <a href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY NC SA 4.0</a>.",
    registered_success: "Inscrit avec succès",
    ballot_created: "Scrutin créé avec succès, notifications en cours d'envoi",
    ballot_closed: "Scrutin cloturé & résultats publiés avec succès. Notifications en cours d'envoi.",
    private_key_missing: "Clé privée introuvable, cloture annulée.",
    please_choose_option: "Veuillez choisir un choix",
    vote_recorded: "Vote enregistré avec succès",
    notifications_sent: "Notifications de {type} envoyées avec succès"
  },
  en: {
    welcome: "Welcome to AVotey",
    subtitle: "A secure voting platform",
    account: "Account",
    greeting: "Hello",
    please_login: "Please log in.",
    logout: "Logout",
    enable_notifications: "Enable Notifications",
    disable_notifications: "Disable Notifications",
    email: "Email:",
    valid_email: "Valid email",
    password: "Password:",
    min_characters: "Minimum 8 characters",
    login: "Login",
    register: "Register",
    email_placeholder: "abc@xyz.com",
    password_placeholder: "******",
    question_placeholder: "Question ... ?",
    scrutins: "Ballots",
    must_login_scrutins: "You must be logged in to interact with ballots",
    gerer_listes: "Manage my lists",
    create_scrutin: "Create a ballot",
    voir_scrutins: "View my ballots",
    voter_scrutin: "Vote for a ballot",
    resultat_scrutin: "Results for a ballot",
    add_list: "Add a list",
    question: "Question:",
    question_help: "This question will be asked to the voters.",
    systeme_vote: "Voting system:",
    uninominal: "Plurality",
    jugement_majoritaire: "Majority Judgment",
    choice: "Choices:",
    choices_help: "These choices will be offered to voters.",
    add_choice: "Add a choice",
    predefined_choices: "Preset choices:",
    add_from_list: "Add from a list",
    binary: "Binary",
    voters: "Voters:",
    voters_help: "These voters can vote in the ballot. Maximum 2 proxies.",
    add_voter: "Add a voter",
    liste_votants: "List of voters:",
    create_ballot: "Create the ballot",
    filters: "Filters:",
    filter_votable: "Votable",
    filter_resultats: "Results",
    filter_createur: "Creator",
    list: "List:",
    organizer: "Organizer",
    question_col: "Question",
    infos: "Info",
    rights: "Rights",
    actions: "Actions",
    n_scrutin: "Ballot #",
    placeholder_via_voir: "Please go through 'View my ballots' to vote",
    help_n_scrutin: "This is the ballot number you'll vote on.",
    systeme_vote_scrutin: "Voting System",
    help_systeme_vote: "Represents the voting system.",
    public_key: "Public key",
    vote_encrypted: "The vote will be encrypted.",
    choice_uninominal: "Plurality choice",
    choose_proposal: "Please choose a proposal.",
    choice_jugement: "Majority Judgment choice",
    votez_proposition: "Please vote for a proposal.",
    vote_for_ballot: "Vote for the ballot",
    results: "Results:",
    absolute: "Absolute",
    percent_voters: "% Voters",
    percent_inscrits: "% Registered",
    repartition: "Distribution",
    mention: "Mention",
    download_pdf: "Download PDF",
    footer_text: "<strong>AVotey</strong> by Jessy FALLAVIER. University project. License: <a href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY NC SA 4.0</a>.",
    registered_success: "Registered successfully",
    ballot_created: "Ballot created successfully, sending notifications",
    ballot_closed: "Ballot closed & results published successfully. Sending notifications.",
    private_key_missing: "Private key not found, closing cancelled.",
    please_choose_option: "Please choose an option",
    vote_recorded: "Vote recorded successfully",
    notifications_sent: "{type} notifications sent successfully"
  },
  kr: {
    welcome: "AVotey에 오신 것을 환영합니다",
    subtitle: "안전한 투표 플랫폼",
    account: "계정",
    greeting: "안녕하세요",
    please_login: "로그인해주세요.",
    logout: "로그아웃",
    enable_notifications: "알림 켜기",
    disable_notifications: "알림 끄기",
    email: "이메일:",
    valid_email: "유효한 이메일",
    password: "비밀번호:",
    min_characters: "최소 8자",
    login: "로그인",
    register: "가입",
    email_placeholder: "abc@xyz.com",
    password_placeholder: "******",
    question_placeholder: "질문 ... ?",
    scrutins: "투표",
    must_login_scrutins: "투표와 상호작용하려면 로그인해야 합니다",
    gerer_listes: "내 목록 관리",
    create_scrutin: "투표 만들기",
    voir_scrutins: "내 투표 보기",
    voter_scrutin: "투표하기",
    resultat_scrutin: "투표 결과",
    add_list: "목록 추가",
    question: "질문:",
    question_help: "이 질문은 투표자들에게 제시됩니다.",
    systeme_vote: "투표 방식:",
    uninominal: "단일 명부",
    jugement_majoritaire: "다수 판단",
    choice: "선택:",
    choices_help: "이 선택지는 유권자에게 제공됩니다.",
    add_choice: "선택 추가",
    predefined_choices: "미리 정의된 선택:",
    add_from_list: "목록에서 추가",
    binary: "이진",
    voters: "투표자:",
    voters_help: "이 투표자들은 투표에 참여할 수 있습니다. 최대 2개의 위임.",
    add_voter: "투표자 추가",
    liste_votants: "투표자 목록:",
    create_ballot: "투표 만들기",
    filters: "필터:",
    filter_votable: "투표 가능",
    filter_resultats: "결과",
    filter_createur: "생성자",
    list: "목록:",
    organizer: "주최자",
    question_col: "질문",
    infos: "정보",
    rights: "권한",
    actions: "작업",
    n_scrutin: "투표 번호",
    placeholder_via_voir: "투표하려면 '내 투표 보기'를 통해 주세요",
    help_n_scrutin: "이것은 당신이 투표할 투표 번호입니다.",
    systeme_vote_scrutin: "투표 방식",
    help_systeme_vote: "투표 방식을 나타냅니다.",
    public_key: "공개 키",
    vote_encrypted: "투표는 암호화됩니다.",
    choice_uninominal: "단일 선택",
    choose_proposal: "제안을 선택하세요.",
    choice_jugement: "다수 판단 선택",
    votez_proposition: "제안을 투표해 주세요.",
    vote_for_ballot: "투표하기",
    results: "결과:",
    absolute: "절대값",
    percent_voters: "% 투표자",
    percent_inscrits: "% 등록자",
    repartition: "분포",
    mention: "등급",
    download_pdf: "PDF 다운로드",
    footer_text: "<strong>AVotey</strong> 제작자 Jessy FALLAVIER. 대학 프로젝트. 라이선스: <a href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY NC SA 4.0</a>.",
    registered_success: "성공적으로 가입되었습니다",
    ballot_created: "투표가 성공적으로 생성되었습니다. 알림 전송 중",
    ballot_closed: "투표가 마감되고 결과가 성공적으로 게시되었습니다. 알림 전송 중.",
    private_key_missing: "개인 키를 찾을 수 없어 마감이 취소되었습니다.",
    please_choose_option: "옵션을 선택해 주세요",
    vote_recorded: "투표가 성공적으로 기록되었습니다",
    notifications_sent: "{type} 알림이 성공적으로 전송되었습니다"
  }
};

function i18n(key, params = {}) {
  const lang = localStorage.getItem('lang') || 'fr';
  let text = (translations[lang] && translations[lang][key]) || translations['fr'][key] || key;
  Object.keys(params).forEach(p => {
    text = text.replace(`{${p}}`, params[p]);
  });
  return text;
}

function applyTranslations() {
  const lang = localStorage.getItem('lang') || 'fr';
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (translations[lang] && translations[lang][key]) {
      el.setAttribute('placeholder', translations[lang][key]);
    }
  });
}

function setLang(lang) {
  localStorage.setItem('lang', lang);
  applyTranslations();
}

document.addEventListener('DOMContentLoaded', () => {
  const lang = localStorage.getItem('lang') || 'fr';
  const select = document.getElementById('langSelector');
  if (select) select.value = lang;
  applyTranslations();
});
